#!/usr/bin/env python3
"""Build-time string compressor for geektaco.

The rendered pages are enormously redundant: `<form method=post action=/`,
`<input type=submit value="[`, `<a href="/` and friends recur up to ten times
across the string table. Measured: 3355 bytes of literals, gzip 1474.

This replaces the plain table with a token dictionary. Bytes 0x01..0x1f that
do not occur in the corpus become token IDs; a greedy pass repeatedly folds
the substring with the highest `count*(len-1) - (len+1)` into a new token.
Tokens may nest, so the expander in render.asm recurses.

Run by hand after editing strings.txt, then commit the generated strtab.inc.
The build does not depend on Python for this step.

    ./mkstr.py strings.txt strtab.inc
"""
import sys, collections, re

ESC = {'\\r': 13, '\\n': 10, '\\0': 0, '\\t': 9, '\\\\': 92}


def unescape(s: str) -> bytes:
    out = bytearray()
    i = 0
    while i < len(s):
        if s[i] == '\\' and i + 1 < len(s):
            two = s[i:i+2]
            if two in ESC:
                out.append(ESC[two]); i += 2; continue
        out.extend(s[i].encode('utf-8')); i += 1
    return bytes(out)


def load(path):
    strings = []
    for line in open(path, encoding='utf-8'):
        line = line.rstrip('\n')
        if not line or line.startswith('#'):
            continue
        name, _, value = line.partition('\t')
        strings.append((name, unescape(value)))
    return strings


def compress(strings):
    blob = b''.join(v for _, v in strings)
    used = set(blob)
    # The expander indexes the offset table with `id - TOK_LO`, so the IDs
    # must be CONTIGUOUS. Take the longest run of control bytes absent from
    # the corpus rather than every absent byte: 10 and 13 occur (CRLF in the
    # HTTP headers) and a gap there would make every later token index wrong.
    best_run = []
    run = []
    for b in range(1, 32):
        if b in used:
            run = []
        else:
            run.append(b)
            if len(run) > len(best_run):
                best_run = list(run)
    free = best_run
    if not free:
        sys.exit('no contiguous run of free control bytes')

    # Work on the concatenation so tokens may span the whole corpus, but keep
    # per-string boundaries so we can slice the result back out afterwards.
    parts = [v for _, v in strings]
    entries = []
    for tok in free:
        joined = b'\x00'.join(parts)
        cnt = collections.Counter()
        for n in range(3, 40):
            for i in range(len(joined) - n):
                sub = joined[i:i+n]
                if 0 in sub:
                    continue
                cnt[sub] += 1
        best = None
        for sub, c in cnt.items():
            if c < 2:
                continue
            gain = c * (len(sub) - 1) - (len(sub) + 1)
            if best is None or gain > best[0]:
                best = (gain, sub)
        if not best or best[0] <= 0:
            break
        entries.append(best[1])
        parts = [p.replace(best[1], bytes([tok])) for p in parts]

    return free, entries, parts


def expand(data, free, entries):
    out = bytearray()
    for ch in data:
        if ch in free[:len(entries)]:
            out += expand(entries[free.index(ch)], free, entries)
        else:
            out.append(ch)
    return bytes(out)


def nasm_bytes(data):
    """Emit as a NASM db line, printable runs quoted, others numeric."""
    out, run = [], []
    for b in data:
        if 32 <= b < 127 and b not in (0x27, 0x5c):
            run.append(chr(b))
        else:
            if run:
                out.append("'" + ''.join(run) + "'"); run = []
            out.append(str(b))
    if run:
        out.append("'" + ''.join(run) + "'")
    return ', '.join(out) if out else '0'


def main():
    src, dst = sys.argv[1], sys.argv[2]
    strings = load(src)
    free, entries, parts = compress(strings)

    # Round-trip or refuse to emit. A silently wrong table would corrupt every
    # page in a way that looks like a rendering bug.
    for (name, orig), got in zip(strings, parts):
        if expand(got, free, entries) != orig:
            sys.exit(f'round-trip FAILED for {name}')

    raw = sum(len(v) for _, v in strings)
    comp = sum(len(p) for p in parts)
    dic = sum(len(e) + 1 for e in entries)

    out = [
        '; Generated by mkstr.py from strings.txt -- do not edit.',
        f'; {raw} bytes of literals -> {comp} compressed + {dic} dictionary.',
        '; Token IDs are control bytes absent from the corpus. Tokens nest, so',
        '; the expander in render.asm recurses. Expansion happens ONLY in',
        '; ob_puts (build-time literals); user data never passes through it.',
        '',
        # TOK_HI must bound the entries that actually exist, not the free
        # list: a gap here makes the expander index past the table.
        'TOK_LO equ %d' % free[0],
        'TOK_HI equ %d' % free[len(entries) - 1],
        '; %d entries, IDs %s' % (len(entries), ','.join(str(f) for f in free[:len(entries)])),
        '',
        'str_dict_off:',
    ]
    off = 0
    offs = []
    for e in entries:
        offs.append(off)
        off += len(e) + 1
    out.append('    dw ' + ', '.join(str(o) for o in offs))
    out.append('')
    out.append('str_dict:')
    for e in entries:
        out.append(f'    db {nasm_bytes(e)}, 0')
    out.append('')
    for (name, _), p in zip(strings, parts):
        out.append(f'{name}: db {nasm_bytes(p)}, 0')
    out.append('')

    open(dst, 'w', encoding='utf-8').write('\n'.join(out))
    print(f'{len(entries)} tokens (IDs {free[0]}..{free[len(entries)-1]})')
    print(f'literals {raw} -> text {comp} + dict {dic} + offsets {2*len(entries)}'
          f' = {comp + dic + 2*len(entries)}')
    print(f'saving {raw - comp - dic - 2*len(entries)} bytes; round-trip OK')


if __name__ == '__main__':
    main()
